sensor:
  # Header Temperature (Indoor / Outdoor)
  - platform: homeassistant
    entity_id: sensor.house_avg
    id: house_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%0.1f°F / %0.1f°F"
            args: [ 'id(house_temperature).state', 'id(outdoor_temperature).state' ]

  - platform: homeassistant
    entity_id: sensor.forever_ct_weather_temperature
    id: outdoor_temperature
    on_value:
      - lvgl.label.update:
          id: temperatures
          text:
            format: "%0.1f°F / %0.1f°F"
            args: [ 'id(house_temperature).state', 'id(outdoor_temperature).state' ]

  # Office Blind Position
  - platform: homeassistant
    entity_id: cover.ikea_of_sweden_praktlysing_cellular_blind
    id: office_blind_position
    attribute: current_position


binary_sensor:

  # Office Evening Scene
  - platform: homeassistant
    id: office_scene_evening
    entity_id: switch.office_evening_stateful_scene
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda return x;

  # Office Dimmed Scene
  - platform: homeassistant
    id: office_scene_dimmed
    entity_id: switch.office_dimmed_stateful_scene
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_dimmed_button
          state:
            checked: !lambda return x;

  # Office Calls Scene
  - platform: homeassistant
    id: office_scene_desk_call
    entity_id: switch.office_calls_stateful_scene
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_calls_button
          state:
            checked: !lambda return x;

  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features
    entity_id: switch.office_features_stateful_scene
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  # Office Blind 100% (Open)
  - platform: template
    id: office_blind_100
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 100) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_open_button
          state:
            checked: !lambda return x;

  # Office Blind 66% (Semi Open)
  - platform: template
    id: office_blind_66
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 66) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_66_button
          state:
            checked: !lambda return x;

  # Office Blind 33% (Semi Closed)
  - platform: template
    id: office_blind_33
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 33) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_33_button
          state:
            checked: !lambda return x;

  # Office Blind 0% (Close)
  - platform: template
    id: office_blind_0
    lambda: |-
      if (id(office_blind_position).has_state()) {
        return abs(id(office_blind_position).state - 0) <= 3;
      }
      return false;
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_close_button
          state:
            checked: !lambda return x;

  # Office Storage Lights
  - platform: homeassistant
    id: office_storage_lights
    entity_id: light.office_storage
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: storage_lights_button
          state:
            checked: !lambda return x;

  # Network Rack
  - platform: homeassistant
    id: network_rack
    entity_id: light.office_network_rack
    trigger_on_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: network_rack_button
          state:
            checked: !lambda return x;
